### ISSUE TITLE
CT phetioID missing from the baseline that was not an archetype: 

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics-basics#24]
```
geometric-optics-basics : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651834935919/geometric-optics-basics/geometric-optics-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics-basics%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1651834935919%22%2C%22timestamp%22%3A1651837838310%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.lensScreen.model.lens.opticShapeProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.lensScreen.model.lens.opticShapeProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651834935919/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.js:172:18)
at validateOverridesFile (phetioAPIValidation.js:91:11)
at onSimStarted (phetioEngine.js:350:28)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:279:22)
at _notifyListeners (Property.ts:211:13)
at set (Property.ts:349:9)
at (Sim.ts:885:14)
id: Bayes Chrome
Snapshot from 5/6/2022, 5:02:15 AM

----------------------------------

geometric-optics-basics : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651834935919/phet-io-wrappers/phet-io-wrappers-tests.html?sim=geometric-optics-basics
3 out of 4 tests passed. 1 failed.
SimTests: geometric-optics-basics: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.lensScreen.model.lens.opticShapeProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.lensScreen.model.lens.opticShapeProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651834935919/assert/js/assert.js:28:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651834935919/chipper/dist/js/tandem/js/phetioAPIValidation.js:157:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651834935919/chipper/dist/js/tandem/js/phetioAPIValidation.js:78:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651834935919/chipper/dist/js/phet-io/js/phetioEngine.js:333:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651834935919/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651834935919/chipper/dist/js/axon/js/Property.js:220:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651834935919/chipper/dist/js/axon/js/Property.js:149:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651834935919/chipper/dist/js/axon/js/Property.js:290:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651834935919/chipper/dist/js/joist/js/Sim.js:669:56

Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.lensScreen.model.lens.opticShapePropertyError: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.lensScreen.model.lens.opticShapeProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1651834935919/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.js:172:18)
at validateOverridesFile (phetioAPIValidation.js:91:11)
at onSimStarted (phetioEngine.js:350:28)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:279:22)
at _notifyListeners (Property.ts:211:13)
at set (Property.ts:349:9)
at (Sim.ts:885:14)
id: Bayes Chrome
Snapshot from 5/6/2022, 5:02:15 AM
```

**Comment by pixelzoom** [comment]
I did rename `geometricOpticsBasics.lensScreen.model.lens.opticShapeProperty` for #402, so there was an API change.  But geometric-optics is not included in perennial/data/phet-io-api-stable, and there is no API file for geometric-optics in phet-io-sim-specific/repos/. So I don't know why this is causing an error.  

@samreid any insight?

**Comment by pixelzoom** [comment]
Ah, I see the issue.  geometric-optics-basics-phet-io-overrides.js was not updated.

**Comment by pixelzoom** [comment]
Addressed in the above commit. I'll leave this open until CT is happy.

**Comment by pixelzoom** [comment]
CT is happy. Closing.
