### ISSUE TITLE
CT phetioID missing from the baseline that was not an archetype

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics-basics#26]
```
geometric-optics-basics : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/geometric-optics-basics/geometric-optics-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics-basics%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661421087152%22%2C%22timestamp%22%3A1661427329915%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.global.view.options.add2FPointsCheckboxProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.global.view.options.add2FPointsCheckboxProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:161:18)
at validateOverridesFile (phetioAPIValidation.ts:86:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:303:22)
at _notifyListeners (ReadOnlyProperty.ts:254:13)
at unguardedSet (ReadOnlyProperty.ts:238:11)
at set (Property.ts:54:10)
at (Sim.ts:910:14)
id: Bayes Puppeteer
Snapshot from 8/25/2022, 3:51:27 AM

----------------------------------

geometric-optics-basics : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/geometric-optics-basics/geometric-optics-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics-basics%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661421087152%22%2C%22timestamp%22%3A1661433635658%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.global.view.options.add2FPointsCheckboxProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.global.view.options.add2FPointsCheckboxProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:161:18)
at validateOverridesFile (phetioAPIValidation.ts:86:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:303:22)
at _notifyListeners (ReadOnlyProperty.ts:254:13)
at unguardedSet (ReadOnlyProperty.ts:238:11)
at set (Property.ts:54:10)
at (Sim.ts:910:14)
id: Bayes Puppeteer
Snapshot from 8/25/2022, 3:51:27 AM

----------------------------------

geometric-optics-basics : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/phet-io-wrappers/state/?sim=geometric-optics-basics&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22geometric-optics-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661421087152%22%2C%22timestamp%22%3A1661427534635%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.global.view.options.add2FPointsCheckboxProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.global.view.options.add2FPointsCheckboxProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:161:18)
at validateOverridesFile (phetioAPIValidation.ts:86:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:303:22)
at _notifyListeners (ReadOnlyProperty.ts:254:13)
at unguardedSet (ReadOnlyProperty.ts:238:11)
at set (Property.ts:54:10)
at (Sim.ts:910:14)
id: Bayes Puppeteer
Snapshot from 8/25/2022, 3:51:27 AM

----------------------------------

geometric-optics-basics : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/phet-io-wrappers/state/?sim=geometric-optics-basics&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22geometric-optics-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661421087152%22%2C%22timestamp%22%3A1661433740100%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.global.view.options.add2FPointsCheckboxProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.global.view.options.add2FPointsCheckboxProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:161:18)
at validateOverridesFile (phetioAPIValidation.ts:86:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:303:22)
at _notifyListeners (ReadOnlyProperty.ts:254:13)
at unguardedSet (ReadOnlyProperty.ts:238:11)
at set (Property.ts:54:10)
at (Sim.ts:910:14)
id: Bayes Puppeteer
Snapshot from 8/25/2022, 3:51:27 AM

----------------------------------

geometric-optics-basics : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/phet-io-wrappers/phet-io-wrappers-tests.html?sim=geometric-optics-basics&phetioDebug=true&phetioWrapperDebug=true
32 out of 33 tests passed. 1 failed.
SimTests: geometric-optics-basics: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.global.view.options.add2FPointsCheckboxProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.global.view.options.add2FPointsCheckboxProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/assert/js/assert.js:28:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/tandem/js/phetioAPIValidation.js:134:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/tandem/js/phetioAPIValidation.js:62:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/phet-io/js/phetioEngine.js:318:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/axon/js/ReadOnlyProperty.js:228:23)
at Property.unguardedSet (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/axon/js/ReadOnlyProperty.js:178:14)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/axon/js/ReadOnlyProperty.js:161:12)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/axon/js/Property.js:52:11)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/joist/js/Sim.js:706:56

Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.global.view.options.add2FPointsCheckboxPropertyError: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.global.view.options.add2FPointsCheckboxProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:161:18)
at validateOverridesFile (phetioAPIValidation.ts:86:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:303:22)
at _notifyListeners (ReadOnlyProperty.ts:254:13)
at unguardedSet (ReadOnlyProperty.ts:238:11)
at set (Property.ts:54:10)
at (Sim.ts:910:14)
id: Bayes Puppeteer
Snapshot from 8/25/2022, 3:51:27 AM

----------------------------------

geometric-optics-basics : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/phet-io-wrappers/phet-io-wrappers-tests.html?sim=geometric-optics-basics
30 out of 31 tests passed. 1 failed.
SimTests: geometric-optics-basics: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.global.view.options.add2FPointsCheckboxProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.global.view.options.add2FPointsCheckboxProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/assert/js/assert.js:28:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/tandem/js/phetioAPIValidation.js:134:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/tandem/js/phetioAPIValidation.js:62:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/phet-io/js/phetioEngine.js:318:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/axon/js/ReadOnlyProperty.js:228:23)
at Property.unguardedSet (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/axon/js/ReadOnlyProperty.js:178:14)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/axon/js/ReadOnlyProperty.js:161:12)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/axon/js/Property.js:52:11)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/chipper/dist/js/joist/js/Sim.js:706:56

Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.global.view.options.add2FPointsCheckboxPropertyError: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.global.view.options.add2FPointsCheckboxProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661421087152/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:161:18)
at validateOverridesFile (phetioAPIValidation.ts:86:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:303:22)
at _notifyListeners (ReadOnlyProperty.ts:254:13)
at unguardedSet (ReadOnlyProperty.ts:238:11)
at set (Property.ts:54:10)
at (Sim.ts:910:14)
id: Bayes Puppeteer
Snapshot from 8/25/2022, 3:51:27 AM
```

**Comment by pixelzoom** [comment]
Fixed, closing.
