### ISSUE TITLE
CT: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics-basics#38]
```
geometric-optics-basics : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675340572765/geometric-optics-basics/geometric-optics-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics-basics%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1675340572765%22%2C%22timestamp%22%3A1675344160197%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.mirrorScreen.view.controls.opticSurfaceTypeRadioButtonGroup.flatRadioButton.enabledProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: geometricOpticsBasics.mirrorScreen.view.controls.opticSurfaceTypeRadioButtonGroup.flatRadioButton.enabledProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675340572765/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:196:18)
at validateOverridesFile (phetioAPIValidation.ts:85:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:309:22)
at _notifyListeners (ReadOnlyProperty.ts:260:13)
at unguardedSet (ReadOnlyProperty.ts:244:11)
at set (Property.ts:54:10)
at (Sim.ts:931:14)
id: Bayes Puppeteer
Snapshot from 2/2/2023, 6:22:52 AM
```

**Comment by veillette** [comment]
Although, there has not been any work on Geometric Optics and Geometric Optics Basics recently , this issue just pop up on CT. It is most likely related to some work in Studio/PhET-IO

**Comment by pixelzoom** [comment]
There have been no changes to geometric-optics since 1/13/2023, so this is almost certainly related to a common-code change. Assigning to PhET-iO team.

**Comment by zepumph** [comment]
From https://github.com/phetsims/sun/issues/826 I believe

**Comment by pixelzoom** [comment]
@samreid I don't see this occurring in CT anymore. https://github.com/phetsims/sun/issues/826 is still open. Has it been addressed enough to make it a non-issue for this sim?

**Comment by samreid** [comment]
I reviewed the PhET-iO instrumentation for the radio button groups in Calculus Grapher, and it seems appropriate.  The `graphSetRadioButtonGroup` has `phetioVisiblePropertyInstrumented: false` but it does have enabledProperty which seems good for this context.  The other ones have both enabled/visible properties.  So I suspect this issue can be closed.
